config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  # get 'vocabularies/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root to: 'vocabularies#index'
  root to: 'top#index'
  resources :vocabularies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :vocabularies
end

app/models/vocabulary.rb
class Vocabulary < ApplicationRecord
  before_validation :set_contentless_name
  
  validates :word, presence: true, length: {maximum: 30}
  validates :meaning, length: {maximum: 30}
  validates :comment, length: {maximum: 100}

  validate :validate_word_not_including_mark

  belongs_to :user
  private
    def validate_word_not_including_mark
      if word&.include?('?') || word&.include?('%') || word&.include?('#')
        errors.add(:word, 'に「－」ハイフン以外の記号は使えません')
      end
    end

    def set_contentless_name
      self.meaning = '意味登録なし' if meaning.blank?
      self.comment = 'コメント登録なし' if comment.blank?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to vocabularies_url, notice: 'ログインしました'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'ログアウトしました'
  end

  private

    def session_params
      params.require(:session).permit(:email, :password)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/vocabularies_controller.rb
class VocabulariesController < ApplicationController
  def index
    @vocabularies = current_user.vocabularies.page(params[:page]).per(15)
  end

  def show
    @vocabulary = current_user.vocabularies.find(params[:id])
  end

  def new
    @vocabulary = Vocabulary.new
  end

  def edit   
    @vocabulary = current_user.vocabularies.find(params[:id])
  end

  def update
    vocabulary = current_user.vocabularies.find(params[:id])
    vocabulary.update!(vocabulary_params)
    redirect_to vocabularies_url, notice: '単語情報を更新しました'
  end

  def create
    # @vocabulary = Vocabulary.new(vocabulary_params)
    @vocabulary = current_user.vocabularies.new(vocabulary_params)
    if @vocabulary.save
      redirect_to @vocabulary, notice: "word「#{@vocabulary.word}」を登録しました"
    else
      render :new
    end
  end

  def destroy
    vocabulary = current_user.vocabularies.find(params[:id])
    vocabulary.destroy
    redirect_to vocabularies_url, notice: "#{vocabulary.word}を削除しました。"
  end

  private
    def vocabulary_params
      params.require(:vocabulary).permit(:word, :meaning, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vocabularies_helper.rb
module VocabulariesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Vocanote
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .navbar.navbar-light.bg-light
      .nabar-brand.logo-name= link_to 'VocaNote', root_path
      
      nav.nav
        - if current_user
          = link_to "ユーザー：#{current_user.name}", user_path(current_user), class: 'nav-link'
          / .nav-item = "ユーザー：#{current_user.name}"
          = link_to '単語一覧', vocabularies_path, class: 'nav-link ml-3'
          - if current_user.admin?
            = link_to 'ユーザー一覧', users_path, class: 'nav-link'
          = link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
        - else
          = link_to '新規登録', new_user_path, class: 'nav-link'
          = link_to 'ログイン', login_path, class: 'nav-link'
        
    .container
      - if flash[:notice].present?
        .alert.alert-success= flash[:notice]
      = yield

app/views/top/index.html.slim
.top VocaNote

app/views/users/edit.html.slim
h1 編集画面

= form_with model: @user, local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control', id: 'user_name'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control', id: 'user_email'
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control', id: 'user_password'
  .form-group
    = f.label :password_confirmation, 'パスワード（確認）'
    = f.password_field :password_confirmation, class: 'form-control', id: 'user_password_confirmation'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/users/index.html.slim
h1 ユーザー一覧

table.table.table-hover
  thead.thead-default
    tr
      th 名前
      th メールアドレス
      th.hide 登録日時
      th.hide 最終更新日時
      th
  tbody
    - @users.each do |user|
      tr
        td= link_to user.name, user_path(user.id)
        td= user.email
        td.hide= user.created_at
        td.hide= user.updated_at
        td
          = link_to '編集', edit_user_path(user), class: 'btn btn-primary'
          = link_to '削除', user, method: :delete, data: {confirm: "ユーザー「#{user.name}」を削除しますがよろしいですか？"}, class: 'btn btn-danger ml-2'

app/views/users/new.html.slim
h1 新規ユーザー登録
- if @user.errors.present?
  ul#error_explanation
    - @user.errors.full_messages.each do |message|
      li = message

= form_with model: @user, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'user_name'
  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :password 
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation
    = f.password_field :passwrod_confirmation, class: 'form-control'
  = f.submit '登録', class: 'btn btn-primary'

app/views/users/show.html.slim
h1.mt-3.mb-3 ユーザー詳細

table.table.table-hover
  tbody
    tr
      th id
      td= @user.id
    tr
      th 名前
      td= @user.name
    tr
      th メールアドレス
      td= @user.email
    tr
      th 登録日時
      td= @user.created_at
    tr
      th 更新日時
      td= @user.updated_at
= link_to '編集', edit_user_url(@user.id), class: 'btn btn-primary'
= link_to '削除', user_url(@user.id), data: {confirm: "ユーザー「#{@user.name}」を削除しますがよろしいですか？"}, class: 'btn btn-danger ml-3'

app/views/vocabularies/_form.html.slim
- if vocabulary.errors.present?
  ul#error_explanation
  - vocabulary.errors.full_messages.each do |message|
    li = message

= form_with model: vocabulary, local: true do |f|
  .form-group
    = f.label :word
    = f.text_field :word, class: 'form-control', id: 'vocabulary_word'
  .form-group
    = f.label :meaning
    = f.text_field :meaning, class: 'form-control', id: 'vocabulary_meaning'
  .form-group
    = f.label :comment
    = f.text_area :comment, row: 5, class: 'form-control', id: 'vocabulary_comment'
  = f.submit '登録', class: 'btn btn-primary'

app/views/vocabularies/edit.html.slim
h1 単語情報の編集

= render partial: 'form', locals: {vocabulary: @vocabulary}

app/views/vocabularies/index.html.slim
= link_to '単語登録', new_vocabulary_path, class: 'btn btn-primary mt-3 mb-3'


.mb-3
  = page_entries_info @vocabularies
table.table.table-hover
  thead.thead-default
    tr
      th 単語
      th 意味
      th
  tbody
    - @vocabularies.each do |vocabulary|
      tr
        td= link_to vocabulary.word, vocabulary, class: 'word'
        td= vocabulary.meaning
        td
          = link_to '編集', edit_vocabulary_path(vocabulary), class: 'btn btn-primary mr-3'
          = link_to '削除', vocabulary_path(vocabulary.id), method: :delete, data: {confirm: "「#{vocabulary.word}」を削除します。よろしいですか？"}, class: 'btn btn-danger'
.mb-3
  = paginate @vocabularies

app/views/vocabularies/new.html.slim
h1.text-center 単語登録画面

= render partial: 'form', locals: {vocabulary: @vocabulary}

app/views/vocabularies/show.html.slim
h1.mt-4.mb-4 = @vocabulary.word


table.table.table-hover
  / tr 
  /   th 単語
  /   td= @vocabulary.word
  tr
    th 意味
    td= @vocabulary.meaning
  tr
    th コメント
    - if @vocabulary.comment
      td= simple_format(h(@vocabulary.comment), {}, sanitize: false, wraper_tag: "div")
      / = @vocabulary.comment
    - else
      td なし
= link_to '編集', edit_vocabulary_path, class: 'btn btn-primary'
= link_to '削除', vocabulary_path(@vocabulary), method: :delete, data: {confirm: "#{@vocabulary.word}を削除します。よろしいですか？"}, class: 'btn btn-danger ml-1'